version: "3"
services:
  api:
    build:
      context: ../api
    volumes:
      - ../api/:/api
    ports:
      - 8000:8000
  app:
    build:
      context: ../app
    # volumes:
    #   - ../app/:/app
    ports:
      - 3000:3000
