version: "3"
services:
  api:
    networks: ['rasa-network']
    build:
      context: ../api
    volumes:
      - ../api/:/api
    ports:
      - 8000:8000

  app:
    build:
      context: ../app
    volumes:
      - ../app:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true

  rasa:
    image: rasa/rasa:3.3.4-full
    networks: ['rasa-network']
    ports:
    - 5005:5005
    volumes:
    - ../RASA-Training/:/app/
    command: >
      run --endpoints /app/endpoints-docker.yml

  rasa-actions-server:
    build:
      context: ../RASA-Training/actions
    networks: ['rasa-network']
    ports:
    - 5055:5055
    volumes:
    - ../RASA-Training/actions:/app/actions

networks: {rasa-network: {}}