version: "3"

services:
  api:
    command:
    [
      "sh",
      "-c",
      "pip3 install debugpy && python3 -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn api:app --reload --host 0.0.0.0 --port 8000",
    ]
    build: ./api
    volumes:
      - ./api/:/api
    ports:
      - 8000:8000